### ISSUE TITLE
Unexpected JaCoCo coverage reports (not taking integration tests into account?)

### ISSUE THREAD

**Issue by kszapsza** [coditory/gradle-integration-test-plugin#159]
## Context

Hi, after upgrading the `integration` plugin from 2.1.0 to 2.2.0, our JaCoCo reports (integrated with `madrapps/jacoco-report`) started reporting invalid coverage percentage. Without changes in code the coverage dropped significantly—probably integration tests are not reported:

<img width="654" alt="image" src="https://github.com/user-attachments/assets/a4941e2d-5376-4b3d-85ac-0bb6cf833c55">

FYI @adriankrupa @bgalek

## Expected behavior

* The test coverage percentage doesn't drop after `integration` plugin bump.

## Observed behavior

* JaCoCo test coverage dropped unexpectedly after plugin version bump, even if there are no changes in production/test code.

## Steps to reproduce

I cannot provide you with full reproduction unfortunately, as the code is proprietary 🙁 

In JVM project with `integration` plugin applied we define a GitHub workflow running JaCoCo and report action:

```yaml
      - run: ./gradlew jacocoTestReport
      - uses: madrapps/jacoco-report@v1.7.1
        if: ${{ github.event_name == 'pull_request' }}
        with:
          paths: |
            ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
          title: Code Coverage
          update-comment: true
          debug-mode: true
```

After bumping the `integration` plugin from 2.1.0 to 2.2.0, the coverage drops as shown on screen attached.

## Your environment

* Library version: 2.2.0
* Link to your project (if it's a public repository): proprietary
